/* ============================================================
   Cognitive Pipeline — Heartbeat WebSocket server (simulation)
   Emits a full state payload every HEARTBEAT_MS (default 3000ms).
   Data is seeded from data/seed.json (generated by extract-seed.mjs
   from the canonical HTML mockup). All values are SIMULATION.
============================================================ */
import { WebSocketServer, WebSocket } from 'ws';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 8787);
const HEARTBEAT_MS = Number(process.env.HEARTBEAT_MS || 3000);

let seed;
try {
  seed = JSON.parse(readFileSync(join(__dirname, 'data', 'seed.json'), 'utf8'));
} catch (e) {
  console.error('FATAL: data/seed.json not found. Run `npm run extract` first.');
  process.exit(1);
}

const pickCount = seed.picks.length;
const stageCount = seed.pipelineStages.length;
console.log(
  `Heartbeat pipeline loaded: ${stageCount} stages, ${pickCount} picks. ` +
  `Listening on ws://0.0.0.0:${PORT}, heartbeat every ${HEARTBEAT_MS}ms.`
);

// One full-state frame. Conviction does a gentle bounded random-walk each tick
// so the UI visibly "pulses"; everything else stays anchored to the seed.
function frame(seq) {
  return {
    seq,
    timestamp: new Date().toISOString(),
    pipelineStages: seed.pipelineStages,
    vetoes: seed.vetoes || [],
    picks: seed.picks.map((p) => {
      const jitter = Math.round((Math.random() - 0.5) * 4); // -2..2
      const conviction = Math.max(1, Math.min(99, Number(p.conviction) + jitter));
      return { ...p, conviction };
    }),
  };
}

const wss = new WebSocketServer({ port: PORT });
let seq = 0;

wss.on('connection', (ws) => {
  console.log(`[+] client connected (${wss.clients.size} total)`);
  ws.send(JSON.stringify(frame(seq++))); // immediate first frame

  const timer = setInterval(() => {
    if (ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify(frame(seq++)));
    }
  }, HEARTBEAT_MS);

  ws.on('close', () => {
    clearInterval(timer);
    console.log(`[-] client disconnected (${wss.clients.size} total)`);
  });
  ws.on('error', (err) => {
    clearInterval(timer);
    console.error('[!] client error:', err.message);
  });
});

wss.on('error', (err) => {
  console.error('[!] server error:', err.message);
});
